[package]
name = "reviews"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "=1.17.0"
ahash = "=0.8.6"
borsh = "=0.9.3"
borsh-derive = "=0.9.3"

[lib]
crate-type = ["cdylib", "lib"]
